### ISSUE TITLE
Getting CORS error

### ISSUE THREAD

**Issue by cehsonu100** [JacobLinCool/LeetCode-Query#50]
Hi I am getting below cors error when I tried to use the library in my react application. Any suggestion?

<img width="1299" alt="Screenshot 2022-10-12 at 6 20 13 AM" src="https://user-images.githubusercontent.com/8523339/195224146-533aa21d-cbdd-466b-8b7e-fe3fb99b3c1d.png">

**Comment by JacobLinCool** [comment]
You can use Cloudflare Workers or some other edge function-like service to do CORS header proxy.
https://developers.cloudflare.com/workers/examples/cors-header-proxy/
