### ISSUE TITLE
LeetCode is not a constructor

### ISSUE THREAD

**Issue by shy-tan** [JacobLinCool/LeetCode-Query#51]
I tried running this example
```
const  LeetCode = require("leetcode-query");
 
const leetcode = new LeetCode();
const user = await leetcode.get_user("username");
```

but I get this error: 
>TypeError: LeetCode is not a constructor

**Comment by JacobLinCool** [comment]
Sorry for the miswritten document, I have updated the README.

The following code should work if you are using CJS:

```js
const { LeetCode } = require("leetcode-query");
 
const leetcode = new LeetCode();

(async () => {
    const user = await leetcode.user("username");
})();
```

Please note that CJS does not allow top-level `await`, which means that you will need to wrap it into an async IIFE.

**Comment by shy-tan** [comment]
Thankyou. Works perfect! I noticed that instead of `const user = await leetcode.get_user("username");` you did `const user = await leetcode.user("username");`. 

Is there some place where these changes are mentioned/ documented. 

Specifically, I'm trying to get the accepted and submitted stats for any LeetCode problems. Hope I did not disturb you much. 😅

**Comment by JacobLinCool** [comment]
The automatically generated document will always reflect the latest change: https://jacoblincool.github.io/LeetCode-Query/

But about the README, you know ... human errors.

I am trying to follow the conventional commitment though I am not good at describing changes: https://github.com/JacobLinCool/LeetCode-Query/commit/a513f8b549dcf856fc5f64aae91ede388bd9220b

> Feel free to close the issue, thanks.

**Comment by shy-tan** [comment]
Thanks!
