### ISSUE TITLE
Is intiating credential every time will create any problem?

### ISSUE THREAD

**Issue by JaySabva** [JacobLinCool/LeetCode-Query#90]
```js
    const credential = new Credential();
    await credential.init(cookie);

    const leetcode = new LeetCode(credential);
```
this block of code is executed many times in my project,
will it create a problem for a user?

**Comment by JacobLinCool** [comment]
Calling `.init` multiple times should not become a problem; it is simply a GET request to the home page of LeetCode.

See 
https://github.com/JacobLinCool/LeetCode-Query/blob/d7e73673de1608e65ddd526a0e4e933155d405e9/src/credential.ts#L43-L47

and

https://github.com/JacobLinCool/LeetCode-Query/blob/d7e73673de1608e65ddd526a0e4e933155d405e9/src/credential.ts#L6-L18
